{% set name = "py-droplets" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py-droplets-{{ version }}.tar.gz
  sha256: 0a225ff43f53a0caf4b0dc4462ef827d0b6ec5c8629d6da8aa2e2f4a0ef203bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - matplotlib-base >=3.1.0
    - numpy >=1.18.0
    - numba >=0.48.0
    - scipy >=1.4.0
    - sympy >=1.5.0
    - py-pde >=0.22.0

test:
  imports:
    - droplets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zwicker-group/py-droplets
  summary: Python package for describing and analyzing droplets in experiments and simulations
  license: MIT
  license_file: LICENSE
  doc_url: https://py-droplets.readthedocs.io
  description: |
    py-droplets provides python code for representing physical droplets using key parameters like position, size, or shape.
    These droplets can also be represented as collections (emulsions) over time.
    Moreover, the package provides methods for locating droplets in microscope images or phase field data from simulations.


extra:
  recipe-maintainers:
    - david-zwicker
