{% set name = "py-droplets" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py-droplets-{{ version }}.tar.gz
  sha256: a3d70d27af30babda952c30801aac6eb38e577a3d610b26028c3b7a53818b1a9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - pip
    - setuptools_scm
  run:
    - matplotlib-base >=3.1.0
    - numba >=0.48.0
    - numpy >=1.23
    - python >=3.8,<3.12
    - py-pde >=0.34.0
    - scipy >=1.4.0

test:
  requires:
    - pip
  imports:
    - droplets
  commands:
    - pip check
    # Check whether the pip version is reported correctly
    - pip list | grep -i {{ name }} | grep {{ version }}

about:
  home: https://github.com/zwicker-group/py-droplets
  summary: Python package for describing and analyzing droplets in experiments and simulations
  license: MIT
  license_file: LICENSE
  doc_url: https://py-droplets.readthedocs.io
  description: |
    py-droplets provides python code for representing physical droplets using key parameters like position, size, or shape.
    These droplets can also be represented as collections (emulsions) over time.
    Moreover, the package provides methods for locating droplets in microscope images or phase field data from simulations.


extra:
  recipe-maintainers:
    - david-zwicker
