{% set name = "py-droplets" %}
{% set version = "0.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: fce4bd78db2cbde6c8b807b752524c7a5d587dcb93744187e30b5bc556577c4f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
  run:
    - h5py >=2.10
    - matplotlib-base >=3.1
    - numba >=0.59
    - numpy >=1.23
    - python >={{ python_min }}
    - py-pde >=0.39
    - scipy >=1.4

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - droplets
  commands:
    - pip check
    # Check whether the pip version is reported correctly
    - pip list | grep -i {{ name }} | grep {{ version }}

about:
  home: https://github.com/zwicker-group/py-droplets
  summary: Python package for describing and analyzing droplets in experiments and simulations
  license: MIT
  license_file: LICENSE
  doc_url: https://py-droplets.readthedocs.io
  description: |
    py-droplets provides python code for representing physical droplets using key parameters like position, size, or shape.
    These droplets can also be represented as collections (emulsions) over time.
    Moreover, the package provides methods for locating droplets in microscope images or phase field data from simulations.


extra:
  recipe-maintainers:
    - david-zwicker
